### ISSUE TITLE
Areas above 50° or below -50° Latitude

### ISSUE THREAD

**Issue by StefanBregenzer** [bbonenfant/dted#1]
Hello,

I am trying to use the **Tile(dted_file)** on SRTM 1arc DTED files.
The publicly available SRTM 1arc data is actually not 1arc by 1arc but 2arc by 1arc, as soon as you are working with areas above 50° Latitude.

This causes the **Tile()** method to fail with the error:
_dted.errors.InvalidFileError: Checksum failed for data block_

When I try to ignore the checksum with **load_data(perform_checksum=False)**, it fails with the error:
_dted.errors.InvalidFileError: All data blocks within a DTED file must begin with 170. Found: 1_

Do I just have to do something differently or is this something you could fix?
It works great otherwise!

Thank you for the help.

**Comment by bbonenfant** [comment]
Thanks for the bug report! I was able to reproduce this and hopefully fix it. If you are able, could you test that you are now able to parse these DTED file using the code on branch `rectangular_resolution_tiles`?

**Comment by StefanBregenzer** [comment]
It works now!
Thank you so much

**Comment by StefanBregenzer** [comment]
Just found one more bug now.
If I try **get_elevation()** with a longitude decimal bigger than .5 it gives me an index out of bounds error.

**Comment by StefanBregenzer** [comment]
The tile.data.shape is now (1801, 3601). I think it should be (3601, 1801) since its (longitude, latitude) and the latitude only has half the information. Right?

**Comment by bbonenfant** [comment]
Ah yes, sorry about that. I tried to get the fix out quickly before going on vacation. I'll spend some more time ironing everything out. I appreciate the patience!

**Comment by bbonenfant** [comment]
I believe I've found the root cause of the bug and addressed it. If possible please try the new changes that I pushed to the `rectangular_resolution_tiles` branch to confirm and then I'll cut a new release

**Comment by StefanBregenzer** [comment]
Seems to be working now
Thank you

**Comment by StefanBregenzer** [comment]
I'm sorry to bother you again...
The shape of the data array is still (1801,3601).
This is wrong in my understanding, since the latitude has half the information and the data shape resembles (long,lat).
Am I wrong?

**Comment by bbonenfant** [comment]
The documentation [at the USGS website](https://www.usgs.gov/centers/eros/science/usgs-eros-archive-digital-elevation-shuttle-radar-topography-mission-srtm-1-arc?qt-science_center_objects=0#qt-science_center_objects) is a little ambiguous, but I believe that the longitudinal resolution of these files is 2 arc-seconds. Using [this DTED file](https://github.com/bbonenfant/dted/blob/primary/test/data/s55_w069_1arc_v3.dt2) as an example, the shape of the data is encoded as 1801 longitudinal records containing 3601 data points. Additionally that file specifies the latitudinal and longitudinal resolutions are 1 and 2 arc-seconds, respectively.

You can inspect the file directly to see the resolution with a command like the following:
```
> hexdump -C -s353 -n8 <dted-file>
00000161  30 30 31 30 30 30 32 30                           |00100020|
00000169
```
where 0010 is the latitudinal resolution in tenths of an arc-second (1 arc-second) and 0020 is the longitudinal resolution in tenths of an arc-second (2 arc-second). 

You can similarly inspect the shape of the DTED data with:
```
hexdump -C -s361 -n8 <dted-file>
00000169  33 36 30 31 31 38 30 31                           |36011801|
00000171

```
where the first four digits are the number of latitudinal lines (3601) and the second four digits for longitude (1801). The initial bug you reported was caused by these numbers were being switched within the library.

I do see that the resolution is of the file is incorrectly being reported by the CLI when inspecting a DTED, so I will fix that. Feel free to reach out again with any more question and report any more bugs you find!

**Comment by StefanBregenzer** [comment]
Thank you for the explanation
Guess I just remembered it wrong
